### ISSUE TITLE
No longer working with aframe 1.5.0

### ISSUE THREAD

**Issue by Turtleted21** [harlyq/aframe-sprite-particles-component#3]
on console : 

Uncaught TypeError: Cannot read properties of undefined (reading 'degToRad')
    at aframe-sprite-particles-component-v1.3.0.js:33:31
    at aframe-sprite-particles-component-v1.3.0.js:1869:3

(anonymous) | @ | aframe-sprite-partic…ponent-v1.3.0.js:33
(anonymous) | @ | aframe-sprite-partic…nent-v1.3.0.js:1869

Thanks

**Comment by Turtleted21** [comment]
@stemkoski

**Comment by Turtleted21** [comment]
FIX : replace THREE.Math by THREE.MathUtils
